#ship animation
#prefuncy.py
import time
import os
Color34 = "\u001b[34m"
Color37 = "\u001b[37m"
# As you can see, its not very optimal
def ship1():
    print("__/\/\__")
    print("-/ __ \-")
    print("  /__\ ")
    print(" /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship2():
    print("   __/\/\__")
    print("   -/ __ \-")
    print("     /__\ ")
    print("    /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship3():
    print("    __/\/\__")
    print("    -/ __ \-")
    print("      /__\ ")
    print("     /____\ ___) ")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship4():
    print("     __/\/\__")
    print("     -/ __ \-")
    print("       /__\ ")
    print("      /____\ ___) ")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship5():
    print("        __/\/\__")
    print("        -/ __ \-")
    print("          /__\ ")
    print("         /____\ ___) ")
print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship6():
    print("           __/\/\__")
    print("           -/ __ \-")
    print("             /__\ ")
    print("            /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship7():
    print("            __/\/\__")
    print("            -/ __ \-")
    print("              /__\ ")
    print("             /____\ ___) ")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship8():
    print("              __/\/\__")
    print("              -/ __ \-")
    print("                /__\ ")
    print("               /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship9():
    print("                __/\/\__")
    print("                -/ __ \-")
    print("                  /__\ ")
    print("                 /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship10():
    print("                  __/\/\__")
    print("                  -/ __ \-")
    print("                    /__\ ")
    print("                   /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship11():
    print("                     __/\/\__")
    print("                     -/ __ \-")
    print("                       /__\ ")
    print("                      /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship12():
    print("                        __/\/\__")
    print("                        -/ __ \-")
    print("                          /__\ ")
    print("                         /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship13():
    print("                         __/\/\__")
    print("                         -/ __ \-")
    print("                           /__\ ")
    print("                          /____\ ___)")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship14():
    print("                           __/\/\__")
    print("                           -/ __ \-")
    print("                             /__\ ")
    print("                            /____\___)")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship15():
    print("                             __/\/\__")
    print("                             -/ __ \-")
    print("                               /__\ ")
    print("                              /____\ ___) ")
print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship16():
    print("                                __/\/\__")
    print("                                -/ __ \-")
    print("                                  /__\ ")
    print("                                 /____\ ___) ")
print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship17():
    print("                                   __/\/\__")
    print("                                   -/ __ \-")
    print("                                     /__\ ")
    print("                                    /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship18():
    print("                                      __/\/\__")
    print("                                      -/ __ \-")
    print("                                        /__\ ")
    print("                                       /____\ ___) ")
    print("\u001b[34m ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \u001b[37m")
def ship19():
    print("                                           __/\/\__")
    print("                                           -/ __ \-")
    print("                                             /__\ ")
    print("                                            /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
def ship20():
    print("                                               __/\/\__")
    print("                                               -/ __ \-")
    print("                                                 /__\ ")
    print("                                                /____\ ___) ")
    print("\u001b[34m -------------------------------------------- \u001b[37m")
os.system("cls")
time.sleep(.1)
ship1()
time.sleep(.5)
os.system("cls")
ship2()
time.sleep(.5)
os.system("cls")
ship3()
time.sleep(.5)
os.system("cls")
ship4()
time.sleep(.5)
os.system("cls")
ship5()
time.sleep(.5)
os.system("cls")
ship6()
time.sleep(.5)
os.system("cls")
ship7()
time.sleep(.5)
os.system("cls")
ship8()
time.sleep(.5)
os.system("cls")
ship9()
time.sleep(.5)
os.system("cls")
ship10()
time.sleep(.5)
os.system("cls")
ship11()
time.sleep(.5)
os.system("cls")
ship12()
time.sleep(.5)
os.system("cls")
ship13()
time.sleep(.5)
os.system("cls")
ship14()
time.sleep(.5)
os.system("cls")
ship15()
time.sleep(.5)
os.system("cls")
ship16()
time.sleep(.5)
os.system("cls")
ship17()
time.sleep(.5)
os.system("cls")
ship18()
time.sleep(.5)
os.system("cls")
ship19()
time.sleep(.5)
os.system("cls")
ship20()
time.sleep(.5)
os.system("cls")
print("or so you thought...")
time.sleep(.5)
os.system("cls")